# Use root/example as user/password credentials
version: '3.8'

services:

  mysql:
    image: mysql:8.2.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    container_name: mysql
    ports:
      - 3305:3306
    environment:
      MYSQL_USER: souza
      MYSQL_PASSWORD: souza
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: souza_vendas_db

