{
 "title": "Sales-Management",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "users COUNT ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"sales-management\", uri=\"/users\"}",
     "legendFormat": "{{method}}/{{overcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "products MAX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"sales-management\", uri=\"/products\"}",
     "legendFormat": "{{method}}/{{overcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{job=\"sales-management\", uri=\"/products/{code}\"}",
     "legendFormat": "{{method}}/{{overcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "products COUNT",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"sales-management\", uri=\"/products\"}",
     "legendFormat": "{{method}}/{{overcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"sales-management\", uri=\"/products/{code}\"}",
     "legendFormat": "{{method}}/{{overcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "categories MAX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"sales-management\", uri=\"/categories\"}",
     "legendFormat": "{{method}}/{{overcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{job=\"sales-management\", uri=\"/categories/{code}\"}",
     "legendFormat": "{{method}}/{{overcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "categories COUNT",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"sales-management\", uri=\"/categories\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"sales-management\", uri=\"/categories/{code}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  }
 ]
}