INSERT INTO products (description, quantity, cost_price, selling_price, observation, category_code) VALUES
                                                                                                        ('Samsung Galaxy S9 Smartphone', 15, 2750, 3299, 'Samsung Galaxy S9+ 6.2-Inch 128GB 6GB RAM', 1),
                                                                                                        ('Swimming Pool', 10, 500, 700, '10,000-Litre Swimming Pool', 3),
                                                                                                        ('Swimming Pool', 10, 600, 800, '20,000-Litre Swimming Pool', 3),
                                                                                                        ('Swimming Pool', 10, 700, 900, '30,000-Litre Swimming Pool', 3),
                                                                                                        ('12-Speed 1000W Blender', 30, 70.90, 139.90, 'Mondial 110V 12-Speed 1000W Turbo Premium Blender', 4),
                                                                                                        ('Electric Table Stove', 8, 60.80, 106.80, 'Agrato 220V 2-Burner Electric Table Stove 2000 Watts', 4),
                                                                                                        ('4-Burner Stove', 20, 280.50, 424.86, 'Atlas Mônaco 4-Burner Stove with Automatic Ignition', 4),
                                                                                                        ('5-Burner Stove', 30, 864, 1164.94, 'Atlas Agile Glass Inox 5-Burner Stove with Triple Flame', 4),
                                                                                                        ('Espresso Coffee Maker', 22, 315.90, 415.90, 'Mondial 110V 15-Bar Coffee Cream Espresso Coffee Maker', 4),
                                                                                                        ('Electrolux Refrigerator', 50, 1000, 1370, 'Electrolux 240-Litre 1-Door Class Refrigerator', 4),
                                                                                                        ('Technos Mens Gold Watch', 35, 180, 249, 'Technos Mens Performer Gold Watch - 2115LAA/4C', 5),
                                                                                                        ('Nibosi Chronograph Watch', 50, 100, 160.50, 'Nibosi Chronograph Watch with Free Shipping Carnival Promotion', 5),
                                                                                                        ('Solid 18k Gold Ring', 60, 210, 299.90, 'Solid 18k 750 7mm Solitaire Gold Ring - Choose Your Color', 5);